services:
  Docker-Update:
    image: funmicra/docker-update:latest
    container_name: Updater
    restart: unless-stopped
    env_file:
      - /opt/infra/env/docker-update.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock